### ISSUE TITLE
It's Not working

### ISSUE THREAD

**Issue by benyaminl** [SakaDream/wox-currency-converter#1]
Hello, this thing isn't working, I tried to convert but nothing showed to my wox..

**Comment by SakaDream** [comment]
Hi, benyaminl

Can you screenshot your problem?
Currency plugin is working fine in my wox

![image](https://user-images.githubusercontent.com/16135427/34077343-6c487ba6-e334-11e7-8568-c9ecee4f6a77.png)

I think the currency web api (www.currencyconverterapi.com) make a long time to respone

**Comment by benyaminl** [comment]
![image](https://user-images.githubusercontent.com/2817332/34078003-fc9a40cc-e343-11e7-8a1b-00959bc6a6d0.png)

It should not, I tried by directly open the url, it's opened, and mine done nothing.. any suggestion?

and I think it should show loading when it's waiting, because without loading, user doesn't know that wox still trying too reach data or such

anyway do you use the free API or the paid one? I think It reach the limit or such?

![image](https://user-images.githubusercontent.com/2817332/34078095-f677e148-e345-11e7-957c-e34faa5ae4f8.png)

![image](https://user-images.githubusercontent.com/2817332/34078144-df1c3ec6-e346-11e7-8119-ce7ae1ed66e3.png)

**Comment by SakaDream** [comment]
Thank you for your suggestion about show loading message
I use the free api, so it reach the limit

**Comment by benyaminl** [comment]
I think you could use http://fixer.io/ or such, it still free and usable for it hhehehe

**Comment by benyaminl** [comment]
or maybe this https://www.amdoren.com/currency-api/ it's seems free, from EU Central seems not covering everything

**Comment by benyaminl** [comment]
hei how about this ? http://www.mycurrency.net/service/rates, you can store it offline bro! update it every 2 hours or such

**Comment by benyaminl** [comment]
https://www.mycurrency.net/page/Free+Currency+Converter+API

**Comment by SakaDream** [comment]
Thank you very much! I will work with my plugin tonight :)

**Comment by SakaDream** [comment]
New version of plugin released! I changed currency exchange source to http://www.xe.com/currencyconverter/ ,and I made a simple crawler library to get the result of the website

**Comment by benyaminl** [comment]
Wow wowowo... you really fast and dedicated to this currency.. ah.. it's a pain when deal with xe.com . Thanks @SakaDream 
![image](https://user-images.githubusercontent.com/2817332/34186973-7c19cb46-e561-11e7-8e29-955c1abffa0a.png) but why mine like this? :octocat: 

![image](https://user-images.githubusercontent.com/2817332/34187059-0a8f7d62-e562-11e7-9bc9-eb6ef8a05f6f.png)

**Comment by benyaminl** [comment]
I think there's a problem with the number, It can't handle floating point, because of it, it generate an error I think, and it's a wrong one, some of it...

![image](https://user-images.githubusercontent.com/2817332/34187214-d2be9aca-e562-11e7-9f76-2180cb434854.png)

the result is from usd to IDR, Indonesian Rupiahs is lower than USD, that doesn't make a sense

**Comment by benyaminl** [comment]
https://finance.google.com/finance/converter?a=123&from=USD&to=IDR

try this

**Comment by SakaDream** [comment]
Thank you benyaminl
And Happy New Year (too late :D )
I found this solution in SOF to fix decimal parsing error
https://stackoverflow.com/questions/5109816/double-parse-with-culture-format

**Comment by benyaminl** [comment]
@SakaDream Ah, that's why.. I see, I've some trouble last time with the decimal, and I set the local, and it's just working as it's, on VB.NET while parse and mine data by using 
`Application.CurrentCulture = New CultureInfo("en-GB")`

**Comment by SakaDream** [comment]
Hello benyaminl!
I fixed that problem 😄 
![image](https://user-images.githubusercontent.com/16135427/34914197-252f0ee8-f940-11e7-9137-b7b2a8727bc2.png)
But I going to Saigon right now, so I will upload the plugin tonight
